package antonafanasjew.libcounter.model;

/**
 * This class is a descriptor of a library.
 * It holds the name of the library.
 * 
 * Additionally, it hosts a method to retrieve the base name.
 * It can be used to strip off the version of the library by providing the version regular expression.
 * (e.g. angular.js for angular-1.2.3.js). 
 * 
 */
public class LibraryInfo {

	private String name;

	public static LibraryInfo fromName(String name) {
		LibraryInfo instance = new LibraryInfo();
		instance.name = name;
		return instance;
	}

	public String getName() {
		return this.name;
	}

	public String getBaseName(String ignorePattern) {
		return getName().replaceAll(ignorePattern, "");
	}

	/* Generated by IDE */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		return result;
	}

	/* Generated by IDE */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		LibraryInfo other = (LibraryInfo) obj;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		return true;
	}

}
